// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config'
import 'dotenv/config'
import config from "./src/utils/env"

export default defineConfig({
  schema: 'src/prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: config.DATABASE_URL,
  },
})
